language: node_js
node_js:
    - '0.10'

after_success:
    - ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter tests | ./node_modules/coveralls/bin/coveralls.js

env:
    global:
        secure: "qDUQlkE9pe1BxlJF8dnUlOGiVzOguIfZL1YDAsHv03JMETo565MFfTsf+wCxXsWE1gUpzcdG+jachmukI4Bmwlp7tTL5tTsDYIEQNvNEbyy25HBktFUAxZY6UJlh2eOHIsI/AuJzOnIbhiSL8LVqqpptGZ/3lT/Ao668UxmFTpw="
